apiVersion: v1
kind: Service
metadata:
  name: transaction-service-backend
  namespace: hamkkebu
  labels:
    app: transaction-service-backend
spec:
  type: ClusterIP
  selector:
    app: transaction-service-backend
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: grpc
      port: 9094
      targetPort: 9094
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-backend-nodeport
  namespace: hamkkebu
  labels:
    app: transaction-service-backend
spec:
  type: NodePort
  selector:
    app: transaction-service-backend
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 31083
      protocol: TCP
