apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hamkkebu-db-secret
  namespace: hamkkebu
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hamkkebu-secret-store
    kind: SecretStore
  target:
    name: hamkkebu-db-secret
    creationPolicy: Owner
  data:
    - secretKey: jdbc-url
      remoteRef:
        key: hamkkebu-source-secrets
        property: db-jdbc-url
    - secretKey: username
      remoteRef:
        key: hamkkebu-source-secrets
        property: db-username
    - secretKey: password
      remoteRef:
        key: hamkkebu-source-secrets
        property: db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hamkkebu-jwt-secret
  namespace: hamkkebu
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hamkkebu-secret-store
    kind: SecretStore
  target:
    name: hamkkebu-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: hamkkebu-source-secrets
        property: jwt-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hamkkebu-keycloak-secret
  namespace: hamkkebu
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hamkkebu-secret-store
    kind: SecretStore
  target:
    name: hamkkebu-keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: hamkkebu-source-secrets
        property: keycloak-client-secret
