apiVersion: v1
kind: Service
metadata:
  name: transaction-service-frontend
  namespace: hamkkebu
  labels:
    app: transaction-service-frontend
spec:
  type: ClusterIP
  selector:
    app: transaction-service-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-frontend-nodeport
  namespace: hamkkebu
  labels:
    app: transaction-service-frontend
spec:
  type: NodePort
  selector:
    app: transaction-service-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30003
      protocol: TCP
