apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hamkkebu

resources:
  - ../../base
  - configmap.yaml
  - external-secret.yaml
  - ingress.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: transaction-service-backend
