apiVersion: v1
kind: Service
metadata:
  name: transaction-service-backend
  labels:
    app: transaction-service-backend
    service: transaction-service
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9093
      targetPort: 9090
      protocol: TCP
  selector:
    app: transaction-service-backend
