apiVersion: v1
kind: Service
metadata:
  name: transaction-service-frontend
  labels:
    app: transaction-service-frontend
    service: transaction-service
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: transaction-service-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
